version: 2
name: 未命名项目
description: ""
global:
  concurrent: false
trigger:
  webhook: gitlink@1.0.0
  event:
    - ref: push
      ruleset:
        - param-ref: branch
          operator: EQ
          value: '"master"'
      ruleset-operator: AND
workflow:
  - ref: start
    name: 开始
    task: start
  - ref: dingtalk_notice_action_card_0
    name: 钉钉通知-ActionCard
    task: dingtalk_notice_action_card@1.0.2
    input:
      boot_webhook_url: ((dingding.dingding_webhook))
      msg_title: '"gitlink定制节点测试"'
      msg_text: trigger.git_event
      single_title: '""'
      single_url: '""'
      btns: '"[]"'
    needs:
      - start
  - ref: end
    name: 结束
    task: end
    needs:
      - dingtalk_notice_action_card_0

